# Generated by Django 4.2.7 on 2024-01-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options_product_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk'], 'permissions': [('set_published', 'Может публиковать товары'), ('set_description', 'Может изменять описание товара'), ('set_category', 'Может изменять категорию товара')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
